export const EndpointsServices = {
  login: 'User/Login',
  Roles: 'Role',
  GET_ROLES_BY_ID: 'Role/GetRolesById/',
  GetModules: 'Module',
  GetModulesByRole: 'ModuleRole',
  postModuleRole: 'ModuleRole',
  GET_ALL_PRIORITY: 'Priority',
  GET_ALL_TYPE_REQUEST_BY_ROLE: 'TypeRequest/GetAllByRoleName',
  GET_ALL_STATUS: 'Status',
  GET_ALL_REGION_BY_COUNTRY_ID: 'Region/GetAllByCountryId/',
  REQUIREMENT: 'Requirement',
  GET_ALL_COUNTRY: 'Country',
  USERS: 'User',
  GET_ALL_USERS_BY_COUNTRY_ID: 'User/GetAllByCountryIdAsync/',
  GET_REQUIREMENT_BY_STATUS: 'Requirement/GetByStatus/',
  GET_ALL_TYPE_REQUESTS: 'TypeRequest',
};
