export const environment = {
  production: true,
  apiUrl: 'https://back-cc-d4cncraae5bdebhz.eastus2-01.azurewebsites.net/api',
  cacheDuration: 28800000,
  menu: [
    {
      text: 'Ordenes de trabajo',
      subText: 'Gestión ordenes de trabajo',
      icon: 'engineering',
      module: 'OrderRequest',
      enabled: true,
      children: [
        {
          text: 'Planeación',
          icon: 'construction',
          module: 'planing',
          enabled: true,
          routerLink: 'request-planning',
        },
        {
          text: 'Requerimientos Generales',
          icon: 'workspaces',
          module: 'request',
          enabled: true,
          routerLink: 'request',
        },
        {
          text: 'Tipo de Requerimiento',
          icon: 'list_alt_add',
          module: 'type-request',
          enabled: true,
          routerLink: 'type-request',
        },
      ],
    },
    {
      text: 'Accesibilidad',
      subText: 'Gestión de seguridad',
      icon: 'account_box',
      module: 'Accesibilidad',
      enabled: true,
      children: [
        {
          text: 'Usuarios',
          icon: 'group',
          module: 'User',
          enabled: true,
          routerLink: 'User',
        },
        {
          text: 'Roles',
          icon: 'perm_identity',
          module: 'Role',
          routerLink: 'Role',
          enabled: true,
        },
        {
          text: 'Modulos por Role',
          icon: 'accessibility',
          module: 'Menu-Role',
          enabled: true,
          routerLink: 'MenuRoles',
        },
      ],
    },
    {
      text: 'Configuración',
      subText: 'Gestión de configuración',
      icon: 'settings',
      module: 'configuracion',
      enabled: true,
      children: [
        {
          text: 'Parametros',
          icon: 'list_alt_check',
          module: 'parameters',
          enabled: true,
          routerLink: 'parameters',
        },
      ],
    },
  ],
  maxlengthInput: 50,
  maxlengthTextArea: 100,
};
