export const RequirementCreateConfig = Object.freeze({
    i18n: {
      title: 'Crear requerimiento',
      titleStep1: 'Seleccione un tipo de requerimiento',
      typeRequest: 'Tipo de requerimiento',
      nextButton: 'Siguiente',
      backButton: 'Atrás',
      cancelButton: 'Cancelar',
      saveButton: 'Guardar',
      resetButton: 'Reiniciar',
      titleStep2: 'Diligenciar requerimiento',
      titleStep3: 'Enviar requerimiento',
      clientText: 'Cliente o empresa',
      clientPlaceholder: 'Ej. ProImportados Inc.,Carl Walcott',
      placeText: 'Lugar',
      placePlaceholder: 'Ej. 1 Main St, New York, NY',
      descriptionText: 'Descripción',
      descriptionPlaceholder: 'Ej. Instalación extra ...',
      contactText: 'Contacto',
      contactPlaceholder: 'Ej. Phil Dunphy +1 333-333-33-33, Mike Gordon +54 555-555-55-55',
      priorityText: 'Prioridad',
      priorityPlaceholder: 'Seleccione una prioridad',
      displayColumns: ['name', 'access'],
    },
  });